INSERT INTO TBL_CARDS (PAN_NUMBER, CREDIT_SCORE) VALUES('AXSSP1122H','3.10');
INSERT INTO TBL_CARDS (PAN_NUMBER, CREDIT_SCORE) VALUES('APPSA3355P','8.50');
INSERT INTO TBL_CARDS (PAN_NUMBER, CREDIT_SCORE) VALUES('APPXA2244X','9.50');
INSERT INTO TBL_CARDS (PAN_NUMBER, CREDIT_SCORE) VALUES('AXVPS7766V','1.50');
INSERT INTO TBL_CARDS (PAN_NUMBER, CREDIT_SCORE) VALUES('ASXPS2121S','5.10');